const {ignore, error} = require('./consts');

module.exports = {
  plugins: [
    'angular'
  ],
  rules: {
    'angular/angularelement': ignore,
    'angular/component-limit': ignore,
    'angular/controller-as': error,
    'angular/controller-as-route': error,
    'angular/controller-as-vm': ignore,
    'angular/controller-name': ignore,
    'angular/deferred': error,
    'angular/definedundefined': ignore,
    'angular/di': ignore,
    'angular/di-order': ignore,
    'angular/di-unused': error,
    'angular/directive-name': ignore,
    'angular/directive-restrict': error,
    'angular/document-service': ignore,
    'angular/empty-controller': error,
    'angular/file-name': ignore,
    'angular/filter-name': ignore,
    'angular/foreach': ignore,
    'angular/function-type': ignore,
    'angular/interval-service': ignore,
    'angular/json-functions': ignore,
    'angular/log': ignore,
    'angular/module-dependency-order': ignore,
    'angular/module-getter': ignore,
    'angular/module-name': ignore,
    'angular/module-setter': ignore,
    'angular/no-angular-mock': error,
    'angular/no-controller': error,
    'angular/no-cookiestore': error,
    'angular/no-http-callback': error,
    'angular/no-inline-template': ignore,
    'angular/no-jquery-angularelement': error,
    'angular/no-private-call': error,
    'angular/no-service-method': ignore,
    'angular/no-services': ignore,
    'angular/on-watch': error,
    'angular/rest-service': ignore,
    'angular/service-name': ignore,
    'angular/timeout-service': ignore,
    'angular/typecheck-array': ignore,
    'angular/typecheck-date': ignore,
    'angular/typecheck-function': ignore,
    'angular/typecheck-number': ignore,
    'angular/typecheck-object': ignore,
    'angular/typecheck-string': ignore,
    'angular/watchers-execution': ignore,
    'angular/window-service': ignore
  }
};
