module.exports = {
  "plugins": [
    "angular"
  ],
  "rules": {
    "angular/angularelement": 0,
    "angular/component-limit": 0,
    "angular/controller-as": 2,
    "angular/controller-as-route": 2,
    "angular/controller-as-vm": 0,
    "angular/controller-name": 0,
    "angular/deferred": 2,
    "angular/definedundefined": 0,
    "angular/di": 0,
    "angular/di-order": 0,
    "angular/di-unused": 2,
    "angular/directive-name": 0,
    "angular/directive-restrict": 2,
    "angular/document-service": 0,
    "angular/empty-controller": 2,
    "angular/file-name": 0,
    "angular/filter-name": 0,
    "angular/foreach": 0,
    "angular/function-type": 0,
    "angular/interval-service": 0,
    "angular/json-functions": 0,
    "angular/log": 0,
    "angular/module-dependency-order": 0,
    "angular/module-getter": 0,
    "angular/module-name": 0,
    "angular/module-setter": 0,
    "angular/no-angular-mock": 2,
    "angular/no-controller": 2,
    "angular/no-cookiestore": 2,
    "angular/no-http-callback": 2,
    "angular/no-inline-template": 0,
    "angular/no-jquery-angularelement": 2,
    "angular/no-private-call": 2,
    "angular/no-service-method": 0,
    "angular/no-services": 0,
    "angular/on-watch": 2,
    "angular/rest-service": 0,
    "angular/service-name": 0,
    "angular/timeout-service": 0,
    "angular/typecheck-array": 0,
    "angular/typecheck-date": 0,
    "angular/typecheck-function": 0,
    "angular/typecheck-number": 0,
    "angular/typecheck-object": 0,
    "angular/typecheck-string": 0,
    "angular/watchers-execution": 0,
    "angular/window-service": 0
  }
};
