module.exports = {
  rules: {
    /// Stylistic Issues
    "array-bracket-spacing": 2,
    "block-spacing": 2,
    "brace-style": [2, "1tbs"],
    "camelcase": 2,
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-style": [2, "last"],
    "computed-property-spacing": 2,
    "consistent-this": [2, "this"],
    "eol-last": 2,
    "func-names": 2,
    "func-style": [2, "declaration", {"allowArrowFunctions": true}],
    "id-length": 0,
    "id-match": 2,
    "indent": [2, 2, {"SwitchCase": 1}],
    "jsx-quotes": [2, "prefer-double"],
    "key-spacing": 2,
    "keyword-spacing": 2,
    "linebreak-style": 2,
    "lines-around-comment": 0,
    "max-len": [2, {
      "ignoreComments": true,
      "ignoreTemplateLiterals": true,
      "ignoreRegExpLiterals": true,
      // Strings longer than 40 symbols (half of standard max-len)
      "ignorePattern": "\"(?=([^\"]|\\\"){40,}\")|'(?=([^']|\\'){40,}')"
    }],
    "max-nested-callbacks": 0, // useless, only function with name call
    "multiline-ternary": [2, "always-multiline"],
    "new-cap": 2,
    "new-parens": 2,
    "no-array-constructor": 2,
    "no-continue": 0,
    "no-inline-comments": 0,
    "no-lonely-if": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-multiple-empty-lines": 2,
    "no-negated-condition": 0,
    "no-nested-ternary": 2,
    "no-new-object": 2,
    "no-restricted-syntax": 2,
    "no-spaced-func": 2,
    "no-ternary": 0,
    "no-trailing-spaces": [2, {"ignoreComments": true}],
    "no-underscore-dangle": 0,
    "no-unneeded-ternary": 2,
    "object-curly-newline": [2, {"consistent": true}],
    "object-curly-spacing": 2,
    "one-var": [2, "never"],
    "operator-assignment": [2, "always"],
    "operator-linebreak": 2,
    "padded-blocks": 0,
    "quote-props": [2, "as-needed"],
    "quotes": [2, "single"],
    "require-jsdoc": 0,
    "semi-spacing": [2, {"before": false, "after": true}],
    "semi": [2, "always"],
    "semi-style": [2, "last"],
    "sort-vars": 0,
    "space-before-blocks": [2, "always"],
    "space-before-function-paren": [2, {"anonymous": "always", "named": "never"}],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": [2, {"words": true, "nonwords": false}],
    "spaced-comment": 0,
    "switch-colon-spacing": [2, {"after": true, "before": false}],
    "wrap-regex": 0
  }
};
